export const LOADING_START = 'LOADING_START';
export const LOADING_FINISH = 'LOADING_FINISH';

export const ADD_CLICK = 'ADD_CLICK';
export const DELETE_CLICK = 'DELETE_CLICK';

export const SET_CURSOR_COORDINATES = 'SET_CURSOR_COORDINATES';
export const SET_CIRCLE_COORDINATES = 'SET_CIRCLE_COORDINATES';
export const SET_AREA_SIZE = 'SET_AREA_SIZE';